name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: create_directory
      run: mkdir build && cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - name: make test
      run: make test
